name: Build LaTeX
on:
  push:
    branches: [ master ]
jobs:
  LaTeX-Building:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `latexmk`
        run: latexmk -interaction=nonstopmode -file-line-error -pdf main

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Compiled PDF
          path: ./main.pdf