name: Build LaTeX
on:
  push:
    branches: [ master ]
jobs:
  LaTeX-Building:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare arXiv tar file
        run: mkdir ../ToArXiv &&
          cp -r ./* ../ToArXiv/ &&
          find . -mindepth 1 -maxdepth 1 -name ".*" -exec rm -rf {} + &&
          tar -cf ToArXiv.tar ../ToArXiv/*

      - name: Run `latexmk`
        run: latexmk -interaction=nonstopmode -file-line-error -pdf main

      - name: Renew arXiv tar file
        run: if [ -f "./main.bbl" ]; then
            tar --append -f ToArXiv.tar main.bbl;
          fi && gzip ToArXiv.tar

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: compiled-PDF
          path: ./main.pdf ./ToArXiv.tar.gz
          if-no-files-found: error
